### ISSUE TITLE
Usage? Output says mkv is not a file

### ISSUE THREAD

**Issue by caleb87** [riweston/fileflows#7]
Found this from your post in makemkv forum which had an example below. I tried it, but it says "indi.mkv is not a file"

The file is there, and I also tried an absolute path which has the same output. 

sudo docker run --rm -it -v /home/caleb/dvconvert:/opt/media ghcr.io/riweston/dovi_tool:latest indi.mkv dvhe.07

**Comment by riweston** [comment]
Weird, what happens if you exec into the container? Something like

```sh
# I'll create a dummy file to test with
$ touch indi.mkv
# There's the file on my mac
$ ls -go
total 0
-rw-r--r--  1   0 15 Mar 07:49 indi.mkv
# exec into the container with local dir mounted
$ docker run --rm -it --entrypoint sh -v $PWD:/opt/media ghcr.io/riweston/dovi_tool:latest
# Note I've dropped the -o argument here
$ /opt/media ls -g
-rw-r--r--    1 root             0 Mar 15 07:49 indi.mkv
```

You should see the file there if it's mounted to the container properly

**Comment by caleb87** [comment]
I changed the absolute path to $PWD and it works! My Chromecast/Jellyfin won't play DV 7, but now I've learned it won't play DV 8 either lol. Guess I'll have to use handbrake to convert out of DV. Kodi can play DV on Chromecast, but Jellyfin can't. 

Thanks for your help! Great docker image should I ever need DV 8 in the future.

```
// fails
sudo docker run --rm -it -v /home/caleb/dvconvert:/opt/media ghcr.io/riweston/dovi_tool:latest indi.mkv dvhe.07
// works
sudo docker run --rm -it -v $PWD:/opt/media ghcr.io/riweston/dovi_tool:latest indi.mkv dvhe.07

```
